add skip checking

diff --git a/.github/workflows/build-ci.yml b/.github/workflows/build-ci.yml
--- a/.github/workflows/build-ci.yml
+++ b/.github/workflows/build-ci.yml
@@ -10,6 +10,15 @@ on:
   workflow_dispatch:
 
 jobs:
+  check_is_skiped_push:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check commit message
+        run: |
+          if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == *'[skin ci]'* ]]; then
+            echo "Commit message contains '[skin ci]'. Skipping workflow."
+            exit 78 # Exit code 78 indicates a neutral status, which skips the workflow
+          fi
   build:
     strategy:
       fail-fast: false
@@ -23,6 +32,7 @@ jobs:
           - os: windows-latest
             rust_target: x86_64-pc-windows-msvc
     runs-on: ${{ matrix.platform }}
+    needs: [check_commit_message]
     steps:
       - name: "[Setup | All] Checkout repository"
         uses: actions/checkout@v4
